### ISSUE TITLE
Minimum required Piwik build should run UI tests and plugin tests

### ISSUE THREAD

**Issue by diosmosis** [piwik/travis-scripts#12]
Currently the minimum_required_piwik job will only execute plugin tests. In order to detect all regressions w/ older Piwiks after changes are made for newer Piwiks, the job should execute UI tests as well.

**Comment by mattab** [comment]
I think the reason we didn't run the UI tests for minimum version is because it is likely the UI will look different (eg. if we changed some color or so in core). 

If we did this, we would likely need two sets of UI tests, one for "minimum" and one for "current"?

**Comment by diosmosis** [comment]
I guess there should be non-screenshot UI tests (ie, angular tests) that test for specific things. Some changes for the UI for 2.15 will break previous versions' UI, but we currently can't detect those things.
